standard/eslint-config-standard

eslintrc.json
See https://github.com/feross/standard/issues/139 for discussion.
=> Stop "react/display-name" being enforced

test/validate-config.js
The config validation code wasn't passing (`foo is defined but never used`) so I added code to make it pass and made the test check that `errorCount === 0`.
=> Make test check for errorCount of 0

eslintrc.json
From: https://github.com/feross/standard/issues/414
=> Removed "arrow-parens" rule

package.json
The rules 'no-duplicate-import' and 'no-useless-escape' that were added 4 days [ago](https://github.com/feross/eslint-config-standard/commit/4fd4c529c86037c22026319b55578584262df850), require a minimum version of eslint 2.5.0.  This introduced a breaking change in the 5.2.0 release for anyone with an eslint version < 2.5.0
=> Update eslint version to ^2.5.0

eslintrc.json
`parserOptions.ecmaVersion`is set to 6 by ESLint when `es6` environment is used, cf.
https://github.com/eslint/eslint/blob/master/conf/environments.js#L98
=> Remove unneeded config for ecmaVersion

test/validate-config.js
While `t.strictEqual` would preserve the exact behaviour, `t.equal` gets the same result for Numbers, and is more concise imho.
=> Replace t.ok with t.equal

eslintrc.json
The replacement rule "no-global-assign" is already enabled.
Fix https://github.com/feross/standard/issues/731
=> Remove deprecated no-native-reassign rule

eslintrc.json
This rule is redundant, since we already enable "no-labels" which is
more restrictive.
=> relax rule "no-extra-label"

README.md
Update documentation to add `eslint-plugin-node` to the Usage documentation, as `node` is specified as a plugin in `eslintrc.json` but is missing from the documentation.
=> Add `eslint-plugin-node` to Usage documentation

package.json
We updated both `eslint-config-standard` and `eslint-plugin-standard` to the latest versions and unfortunately this doesn't work with npm 2 (Node.js 4) as `eslint-config-standard` has a peerDependency on [`eslint-plugin-standard@^2.2.0`](https://github.com/feross/eslint-config-standard/blob/9b1df3a0c5f338dfaafd33b817f22b385f397b8f/package.json#L55).
This should fix the issue.
=> Update eslint-plugin-standard to version 3.0.0

eslintrc.json
Should fix https://github.com/standard/standard/issues/918
=> Don't mark //= comments as errors

package.json
Note: This is merging to a new **v11** branch for now instead of **master**
I went through the changelog for `eslint` and `eslint-plugin-node` and noted the changes that affect our rules:
- eslint 4 rule updates that affect `standard`:
- The `indent` rule is more strict.
- The `padded-blocks` rule is more strict.
- The `space-before-function-paren` rule is more strict.
- The `no-multi-spaces` rule is more strict.
- Minor improvements to `no-extra-parens`, `no-unexpected-multiline`, `no-regex-spaces`, and `space-unary-ops`
- eslint-plugin-node rule updates:
- The `no-deprecated-api` rule updated to with node 8 support and better node 6 support.
edit: add `space-unary-ops`
=> update to eslint v4 and eslint-plugin-node v5

package.json
Improves URLs for consistency and speed (one less redirect to load), but also improves the repo URL by using HTTPS (secure) over `git://` (insecure).
=> Update URLs in package.json to use 'standard' org

package.json
Just adds the linter to the repo
=> Apply the eslint rules to this repo

eslintrc.json
https://github.com/benmosher/eslint-plugin-import/blob/afe0a3a52423cc6b49d2fdad498115be2990d706/docs/rules/no-named-default.md
Makes sense to me.
=> add rule import/no-named-default

README.md
Fixes #92 ("Mention eslint --init in documentation").
cc @feross
=> Add a simpler installation process to the README

eslintrc.json
Per discussion [here](https://github.com/standard/standard/issues/609#issuecomment-400826566) (https://github.com/standard/standard/issues/609#issuecomment-400826566) it seems like it's both time for this to happen, and that the community prefers `"always"`.
ping @feross @Flet @dcousens
=> Add the object-curly-spacing rule

eslintrc.json
=> Add rule "prefer-const"

eslintrc.json
Per discussion here 
https://github.com/standard/standard/issues/609#issuecomment-419025829 and issue here https://github.com/standard/standard/issues/1203, add "array-bracket-spacing" rule set to "never".
=> Add the array-bracket-spacing rule

eslintrc.json
Babel 7 has support for the proposed pipeline operator. See 
- https://www.npmjs.com/package/@babel/plugin-proposal-pipeline-operator
- https://github.com/tc39/proposal-pipeline-operator
Right now, standard requires this linebreak to occur at the end of the line, which is an uncommon place for a pipeline operator compared to other languages implementing them (the previous link to the TC39 proposal links out to various examples of other languages), where it is very common to see this operator occurring at the start of a new line.
This PR adds an exception for the pipeline operator, next to the ternary operator exception already being part of standard.
=> Add an exception so a linebreak should happen before the pipeline operator

eslintrc.json
=> Add rule no-void

eslintrc.json
Adds the rule `no-case-declarations`.
Ecosystem impact:
```
1..186
```
**Failing packages:**
**References:**
- [ESLint documentation for no-case-declarations](https://eslint.org/docs/rules/no-case-declarations)
- Closes standard/standard#1211
=> Add rule no-case-declarations

eslintrc.json
no-labels bans all labels, so it's not necessary to enable no-label-var (which lints how labels are used). Additionally, our settings for no-labels are equivalent to the defaults.
=> Remove redundant no-label-var rule

eslintrc.json
Following discussion in https://github.com/standard/standard/issues/1442, and subsequent action in the TypeScript side here: https://github.com/standard/eslint-config-standard-with-typescript/pull/253
=> Remove no-return-await rule

eslintrc.json, package.json
This should (probably, right?) be a breaking change since we are changing a peer dependency.
=> Update to rules moved out from ESLint 7

eslintrc.json
As per https://eslint.org/docs/rules/no-negated-in-lhs , `no-negated-in-lhs` was replaced by [`no-unsafe-negation`](https://eslint.org/docs/rules/no-unsafe-negation), which you already have (as `"no-unsafe-negation": "error"`).
(Noticed this while introspecting on a derivative config object.)
=> Remove deprecated rule no longer in standard

eslintrc.json
Fixes standard/standard#1436
The ecmaVersion in parserOptions is only for setting syntax support.
From the docs: https://eslint.org/docs/user-guide/configuring
> supporting ES6 syntax is not the same as supporting new ES6 globals
Setting the es2020 env will actually set the globals:
> adds all ECMAScript 2020 globals and automatically sets the ecmaVersion parser option to 11.
=> Fix es2020 globals not being recognized

package.json
Allow `eslint-plugin-promise` v5 as peer dependency.
Fixes the following use case https://github.com/netlify/eslint-config-node/pull/160#issuecomment-817407644 and extracted from https://github.com/standard/eslint-config-standard/pull/183 to separate concerns.
=> fix: allow eslint-plugin-promise v5 as peer dependency

.github/workflows/ci.yml, .npmignore, .travis.yml, README.md
**What changes did you make? (Give an overview)**
This allows us to be consistent across the organization, we're slowly migrating to GitHub Actions.
Related: https://github.com/standard/eslint-config-standard-with-typescript/pull/530, https://github.com/standard/standard-engine/pull/233, https://github.com/standard/standard-engine/pull/233
=> ci: change Travis to GitHub actions

.eslintrc.json, README.md, package.json
ESLint v8 has been released stable. :tada:
It's time to support `eslint@8`.
See: https://eslint.org/blog/2021/10/eslint-v8.0.0-released
Blocked by:
Closes #192
=> feat: support eslint v8

.github/workflows/ci.yml
The core actions use floating tags for the major release lines to keep up the latest changes
=> ci: unpin core actions

.eslintrc.json, package.json, test/validate-config.js
Turns out we should have set the `parserOptions`to `2022` rather than `2021`.
This PR fixes that + adds a test for it 👍 
Fixes https://github.com/standard/standard/issues/1548
=> fix: allow top-level `await` support
